CONF_RELAY_1 = "relay_1"
CONF_RELAY_2 = "relay_2"
CONF_RELAY_3 = "relay_3"
CONF_RELAY_4 = "relay_4"
CONF_COMMAND = "command"
CONF_BAUD_RATE = "baud_rate"
CONF_STOP_BITS = "stop_bits"
CONF_PARITY = "parity"
CONF_DATA_BITS = "data_bits"
CONF_PORT = "port"
CONF_DURATION_MS = "duration_ms"
CONF_REPEAT_COUNT = "repeat_count"

DOMAIN = "rfx9600"
DEFAULT_NAME = "RFX9600 Relay"
SERVICE_SEND_RS232 = "send_rs232"
